### ISSUE TITLE
Edit/Remove Printers

### ISSUE THREAD

**Issue by EliteCodexer** [rluzuriaga/Open-Printer-Management-System#5]
What is the best method for adding or removing printers that I've added. Editing the database?

**Comment by rluzuriaga** [comment]
@EliteCodexer Sorry haven't checked on this project in a while.
Adding a printer is pretty easy, there is an `Add Printer` button on the navbar.
Removing a printer can only be done from the backend. To access the backend you would need to add a Django superuser first (https://www.geeksforgeeks.org/how-to-create-superuser-in-django/).
Once the superuser is created, the admin link is http://x.x.x.x/admin

**Comment by rluzuriaga** [comment]
@EliteCodexer I will work on making a superuser when installing the application.

**Comment by rluzuriaga** [comment]
@EliteCodexer I added the code to add the superuser when running the setup script.
